#!/usr/bin/env bash
# Build a raw ext4 rootfs image for the guest by cloning the host's
# ostree deployment. Yields a self-contained 4 GB image that crosvm can
# mount as --rwroot, with the SAME glibc/coreutils as the host (zero
# userspace drift between host and guest — the "same kernel, same
# userspace" control variable our EXPERIMENT.md commits to).
#
# Run on the target host (N90 / Kaitian) as root or via sudo.
#
# Output: $OUT (default ~/pvm/rootfs.img)
set -euo pipefail

OUT="${OUT:-$HOME/pvm/rootfs.img}"
SIZE_GB="${SIZE_GB:-4}"
LMBENCH_SRC="${LMBENCH_SRC:-/data/lmbench-3.0-a9}"

if [ "$(id -u)" -ne 0 ]; then
  echo "[mkrootfs] need root; re-exec with sudo" >&2
  exec sudo -E OUT="$OUT" SIZE_GB="$SIZE_GB" LMBENCH_SRC="$LMBENCH_SRC" bash "$0" "$@"
fi

# locate the live ostree deployment (its .0 dir is a flat usable rootfs tree)
DEPLOY=$(ls -d /sysroot/ostree/deploy/*/deploy/*.0 2>/dev/null | head -1)
[ -d "$DEPLOY" ] || { echo "[mkrootfs] no ostree deploy found"; exit 1; }
echo "[mkrootfs] cloning from: $DEPLOY"

mkdir -p "$(dirname "$OUT")"
truncate -s "${SIZE_GB}G" "$OUT"
mkfs.ext4 -F -q -L pvm-root "$OUT"

MNT=$(mktemp -d)
mount -o loop "$OUT" "$MNT"
trap 'umount "$MNT" 2>/dev/null; rmdir "$MNT" 2>/dev/null' EXIT

echo "[mkrootfs] rsync deploy → image (excludes: volatile, host-only, big caches, non-essentials)"
rsync -aHAX --numeric-ids \
  --exclude='/proc/*' --exclude='/sys/*' --exclude='/dev/*' --exclude='/run/*' \
  --exclude='/tmp/*'  --exclude='/var/tmp/*' \
  --exclude='/var/cache/*' --exclude='/var/log/*' \
  --exclude='/home/*' --exclude='/root/.cache' --exclude='/root/.local' \
  --exclude='/data/*' --exclude='/sysroot/*' --exclude='/boot/*' \
  --exclude='/backup/*' --exclude='/var/lib/snapd' \
  --exclude='/usr/share/kylin-ai' \
  --exclude='/usr/share/fonts' \
  --exclude='/usr/share/wallpapers' \
  --exclude='/usr/share/sounds' \
  --exclude='/usr/share/icons' \
  --exclude='/usr/share/locale/[^e]*' \
  --exclude='/usr/share/man' --exclude='/usr/share/doc' \
  --exclude='/usr/share/help' --exclude='/usr/share/themes' \
  --exclude='/usr/lib/firmware/iwlwifi*' \
  --exclude='/usr/lib/firmware/qcom*' \
  --exclude='/usr/lib/firmware/amdgpu*' \
  --exclude='/usr/lib/firmware/i915*' \
  --exclude='/opt/kingsoft' --exclude='/opt/Tencent' \
  --exclude='/opt/baidunetdisk' --exclude='/opt/wpsoffice' \
  --exclude='/usr/lib/x86_64-linux-gnu' \
  --exclude='/usr/lib/firmware' \
  --exclude='/usr/src' \
  --exclude='/usr/share/kylin-*' \
  --exclude='/var/lib/flatpak' \
  --exclude='/var/opt/*' \
  --exclude='/snap' --exclude='/var/snap' \
  "$DEPLOY/" "$MNT/"

# ensure the mountpoint stubs exist even though we excluded their contents
mkdir -p "$MNT"/{proc,sys,dev,run,tmp,var/tmp,var/log,var/cache,home,boot,data,sysroot}
chmod 1777 "$MNT/tmp" "$MNT/var/tmp"

# Phase 2: copy the live host's /etc on top. ostree distributes immutable
# config in /usr/etc and stores the runtime-merged /etc as an overlay; only
# the live mount shows the actual /etc/passwd, /etc/shadow, /etc/group etc.
# Without this step, the guest has no users → PAM rejects every login.
echo "[mkrootfs] overlaying live /etc (for /etc/passwd, /etc/shadow, ...)"
rsync -aHAX --numeric-ids --delete \
  --exclude='/etc/fstab' \
  --exclude='/etc/machine-id' --exclude='/etc/hostname' \
  --exclude='/etc/ssh/ssh_host_*' \
  --exclude='/etc/systemd/system/serial-getty@ttyS0.service.d' \
  /etc/ "$MNT/etc/"

# write a minimal guest fstab (single root on /dev/vda; tmpfs left to systemd defaults)
cat > "$MNT/etc/fstab" <<EOF
# Generated by mkrootfs.sh for crosvm guest
/dev/vda    /    ext4    rw,relatime    0 1
proc        /proc    proc    nosuid,nodev,noexec,relatime    0 0
sysfs       /sys     sysfs   nosuid,nodev,noexec,relatime    0 0
devtmpfs    /dev     devtmpfs    nosuid,relatime    0 0
EOF

# reset machine identity. machine-id must be a valid 32-hex-char string for
# systemd / dbus to come up cleanly — empty file makes systemd regenerate on
# boot, but a few services check before that runs. Pre-fill a static one.
echo "00112233445566778899aabbccddeeff" > "$MNT/etc/machine-id"
echo "pvm-guest" > "$MNT/etc/hostname"
rm -f "$MNT"/etc/ssh/ssh_host_*

# --- auto-login on the serial console (ttyS0) ---
# crosvm exposes its --serial console as /dev/ttyS0 in the guest. Override
# the generic serial-getty@ unit to autologin root, then enable it for ttyS0.
mkdir -p "$MNT/etc/systemd/system/serial-getty@ttyS0.service.d"
cat > "$MNT/etc/systemd/system/serial-getty@ttyS0.service.d/autologin.conf" <<'EOF'
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin root --noclear %I 115200 vt220
EOF
mkdir -p "$MNT/etc/systemd/system/getty.target.wants"
ln -sf /lib/systemd/system/serial-getty@.service \
       "$MNT/etc/systemd/system/getty.target.wants/serial-getty@ttyS0.service"

# --- guest entrypoint: drop a script that runs on root login ---
# If /opt/lmbench/autorun marker exists, fire the bench; otherwise just
# leave the user at a shell. Lets us toggle automation by `touch` / `rm` of
# the marker without reflashing the rootfs.
cat > "$MNT/root/.bash_profile" <<'EOF'
# Auto-run benchmark if marker is set. Manual override: `touch /tmp/skip-bench`.
if [ -f /opt/lmbench/autorun ] && [ ! -f /tmp/skip-bench ]; then
  echo "[guest] /opt/lmbench/autorun present — starting benchmark"
  /opt/lmbench/bench-in-guest.sh 2>&1 | tee /opt/lmbench/results/last-run.log
  echo "[guest] benchmark done — type 'reboot -f' or 'halt -f' to exit"
fi
EOF
chmod 644 "$MNT/root/.bash_profile"

# mask services that have no business in a benchmark guest
for svc in snapd snapd.socket NetworkManager systemd-resolved chrony systemd-timesyncd \
           ModemManager bluetooth cups cups-browsed avahi-daemon unattended-upgrades \
           lightdm gdm sddm kylin-os-manager-daemon; do
  ln -sf /dev/null "$MNT/etc/systemd/system/${svc}.service" 2>/dev/null || true
done

# bake lmbench tree (with binaries) into the guest at the canonical path
if [ -d "$LMBENCH_SRC" ]; then
  echo "[mkrootfs] copying lmbench tree into /opt/lmbench"
  mkdir -p "$MNT/opt/lmbench"
  rsync -aH \
    --exclude='results/' \
    --exclude='guest/rootfs.img' --exclude='guest/crosvm' \
    --exclude='guest/pvmfw*' --exclude='guest/pvm-manage' \
    --exclude='.git/' --exclude='.remember/' \
    "$LMBENCH_SRC/" "$MNT/opt/lmbench/"
else
  echo "[mkrootfs] WARN: $LMBENCH_SRC not found; lmbench not baked in" >&2
fi

echo "[mkrootfs] done: $OUT ($(du -h "$OUT" | cut -f1) sparse / $(du -h --apparent-size "$OUT" | cut -f1) logical)"
